version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file: .env
    environment:
      - REACT_APP_API_URL=http://backend:5000
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
    ports:
      - "3000:3000"