# Maps DB field names to readable questions
SURVEY_QUESTION_MAP = {
    "home_lang_ans": "What language(s) do you speak at home?",
    "comfortability_ans": "I feel comfortable at school.",
    "isolated_school_ans": "At school, I feel isolated because of my opinions.",
    "criticise_school_ans": "When someone criticises the school, it feels like a personal insult.",
    "opinion_school_ans": "At school, my opinion doesn’t count for much.",
    "bullying_ans": "At this school, bullying is not tolerated at all.",
    "future_ans": "I believe that what I learn at school will help me in my future.",
    "covid_ans": "I feel worried that COVID-19 has had a big impact on my education.",
    "how_happy_ans": "How happy are you with your life as a whole?",
    "nervous_ans": "How often did you feel nervous?",
    "hopeless_ans": "How often did you feel hopeless?",
    "restless_ans": "How often did you feel restless or fidgety?",
    "depressed_ans": "How often did you feel so depressed nothing could cheer you up?",
    "effort_ans": "How often did everything feel like an effort?",
    "worthless_ans": "How often did you feel worthless?",
    "intelligence1_ans": "I have a certain amount of intelligence and can’t really do much to change it.",
    "intelligence2_ans": "I can learn new things, but I can’t really change my basic intelligence.",
    "man_chores_opinion": "A man shouldn't have to do household chores.",
    "man_violence_opinion": "Men should use violence to get respect if necessary.",
    "man_sexual_opinion": "A real man should have as many sexual partners as he can.",
    "man_fears_opinion": "A man who talks a lot about worries and fears shouldn't really get respect.",
    "gay_man_opinion": "A gay guy is not a 'real man'.",
    "soft_sport_boys_ans": "Boys who don’t play sport are ‘soft’.",
    "gender_diff_ans": "Women and men are just naturally different in the way they think and behave.",
    "nerds_ans": "Boys who get good marks at school are ‘nerds’.",
    "men_better_stem_ans": "Men are better than women at science, engineering, medicine and technology."
}
